name: Build

on:
  pull_request_target:
    branches: [ "main" ]
  workflow_dispatch: { }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        cache: true
    - name: Build HoloInsight Collector
      shell: bash
      run: |
        export GOOS=linux
        export GOARCH=amd64
        make otelcontribcol
